USE [master]
GO

CREATE DATABASE [NESS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NESS', FILENAME = N'E:\Programas instalados\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NESS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NESS_log', FILENAME = N'E:\Programas instalados\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NESS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NESS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NESS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NESS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NESS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NESS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NESS] SET ARITHABORT OFF 
GO

ALTER DATABASE [NESS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NESS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NESS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NESS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NESS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NESS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NESS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NESS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NESS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NESS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NESS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NESS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NESS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NESS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NESS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NESS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NESS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NESS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NESS] SET  MULTI_USER 
GO

ALTER DATABASE [NESS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NESS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NESS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NESS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NESS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NESS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NESS] SET  READ_WRITE 
GO


